### ISSUE TITLE
Add batching based on payload size

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-android-tracker#110]

**Comment by jbeemster** [comment]
What kind of threshold are we looking at keeping payloads below for this ticket?  I also assume this would only be relating to POST requests yes?

**Comment by alexanderdean** [comment]
Hmm, I think we should make it user-configurable? We will keep increasing the payload size supported by our collectors so this should be tunable I guess depending on the collector version a user is using...

**Comment by jbeemster** [comment]
@alexanderdean what do we in the case of a GET request being too big?  Do we bin it or let the collector deal with it?

**Comment by alexanderdean** [comment]
Good Q. @fblundun - what does the JS Tracker do?

**Comment by jbeemster** [comment]
Also if the collectors are going to check the size of the payload regardless does this not create a bit of double work?  Do all the collectors check payload size?

**Comment by alexanderdean** [comment]
Collectors don't formally check payload size. Collectors can reject events which exceed their tolerated payload size.

I know we had an issue at one stage where a collector was rejecting an oversized GET and that was backing up the events being sent from the browser.

**Comment by alexanderdean** [comment]
@jbeemster - the JS tickets:

* https://github.com/snowplow/snowplow-javascript-tracker/issues/359
* https://github.com/snowplow/snowplow-javascript-tracker/issues/362

**Comment by fblundun** [comment]
The JS Tracker currently doesn't check the size of GETs.

For POSTs: [this function](https://github.com/snowplow/snowplow-javascript-tracker/blob/master/src/js/out_queue.js#L149) is used to determine the size of the request body. maxPostBytes is the configurable limit and it defaults to 40000. If a single event is too big, the tracker attempts to fire it once and then forgets about it. Otherwise it gets added to the localStorage queue, along with metadata about its size in bytes. When events are sent in batches, each batch is less than maxPostBytes in size.
