### ISSUE TITLE
Comment demo-app's build.gradle to explain why it shouldn't be copied

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-android-tracker#158]
More realistic for an end-user than current approach, which seems to pull in local projects...

**Comment by jbeemster** [comment]
It is done like that because there are conflicts pulling in both RX and Classic otherwise...

**Comment by alexanderdean** [comment]
Good reason!

**Comment by alexanderdean** [comment]
Why it shouldn't be copied:

1. It uses projects
2. It pulls in both -rx and -classic

**Comment by alexanderdean** [comment]
(I am currently supporting a customer who has copied the build.gradle)

**Comment by jbeemster** [comment]
I'll make example build.gradles for both projects so it can be copy and pasted.

**Comment by jbeemster** [comment]
So I have learnt a few things about our gradle setup:

1. You cannot currently use a @aar dependency setup as we do not have the `core` as an available dependency, it is project linked into both classic and rx when we make the jar.
  - As such we should probably start publishing the core along with classic and rx.
2. Plus dependencies do not seem to work for 0.5 just yet.  Maybe because there is only 0.5.0 out as of yet? (I am referring to 0.5.+ in place of 0.5.0)

This is my current build.gradle for the demonstration app; using the @aar I can use proper imports instead of project imports, as @aar does not bring in the core.  A better solution here would be to use @aar import style for core, rx and classic but depends on point one:

```java
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])

    // Android Application Dependencies
    compile 'com.android.support:support-v4:22.0.0'
    compile 'com.android.support:appcompat-v7:22.2.0'

    // Analytics for retrieving IDFA
    compile 'com.google.android.gms:play-services-analytics:7.5.0'

    // Common Tracker Dependencies
    compile 'com.squareup.okhttp:okhttp:2.1.0'

    // RxJava Dependency
    compile 'io.reactivex:rxjava:1.0.11'

    // Classic and Rx Libraries
    compile 'com.snowplowanalytics:snowplow-android-tracker-rx:0.5.0@aar'
    compile 'com.snowplowanalytics:snowplow-android-tracker-classic:0.5.0'
}
```

**Comment by alexanderdean** [comment]
We are now hosting the -core:0.5.0@aar...

Could you do the example build.gradles in a branch so I can share with a customer?

**Comment by jbeemster** [comment]
I can put them in the setup guide instead if you like?

**Comment by alexanderdean** [comment]
That would be great!
