### ISSUE TITLE
Programatically populate the Useragent string

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow-android-tracker#234]
http://stackoverflow.com/questions/3626071/retrieve-user-agent-programatically/5261472#5261472

**Comment by alexanderdean** [comment]
Hey @jbeemster - do you think we should populate this by default for Android? (Still allowing manual override obviously.) It sounds like macOS basically does this...

**Comment by jbeemster** [comment]
We should add it as a builder option with the option to then manually override it still there.  The NSUrl library in Objective-C does populate this automatically already.

**Comment by plastiv** [comment]
Current default user agent `okhttp/4.12` provided by snowplow Android tracker seems to be marked as bot net with snowplow Backend. I assume it because of lack of variety for every request from every app instance.

I would consider to provide user agent with Android platform version, phone manufacture build and snowplow tracker version by default. Or at least mention in setup readme that user agent is required to be changed. We have now production traffic marked as bot spam.

**Comment by AlexBenny** [comment]
Thanks @plastiv for raising up this old issue with the IAB enrichment.
It has been recently fixed in the [version 1.4.0](https://github.com/snowplow/snowplow-android-tracker/releases/tag/1.4.0).
You can find further details here: https://snowplowanalytics.com/blog/2020/03/10/snowplow-android-tracker-1.4.0-released/#iab

About the original topic: it's possible to customise the User Agent used by the Android tracker by setting the User Agent of the tracker’s Subject: [`setUserAgent`](https://github.com/snowplow/snowplow-android-tracker/blob/0ab5eeaf15eea7ca9562cf96dd28a034b97c668c/snowplow-tracker/src/main/java/com/snowplowanalytics/snowplow/tracker/Subject.java#L211).
