### ISSUE TITLE
Add tracking of Play Store referer

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-android-tracker#249]
Mixpanel handles it (https://mixpanel.com/help/reference/android#referrer_tracking) by adding a listener and setting it as a super property.

We could add a similar listener and then fire an event - what should the event be called?

**Comment by htmathias** [comment]
Bear in mind, you can pass any string through referrer, but GA tells users to follow UTM parameters with source being a required string, so you could parse this by default.
(https://developers.google.com/analytics/devguides/collection/android/v4/campaigns#google-play-url-builder)

Another point to consider is that we actually use our own custom referrer model rather than UTM, FB and other ad agencies also do this, which is mostly a series of key:value pairs, we'd have to parse that in the SQL modelling or in the listener. Not the end of the world, but we'd maybe have to do our own 'attribution event' anyway with a schema.

**Comment by alexanderdean** [comment]
Thanks @htmathias , that's helpful context...
