### ISSUE TITLE
Need dependency of "androidx.lifecycle:lifecycle-process"

### ISSUE THREAD

**Issue by joki123123** [snowplow/snowplow-android-tracker#392]
Tracker uses ProcessLifecycleOwner().get()

**Comment by AlexBenny** [comment]
Hi @joki123123 
The last version of the tracker (1.4.2) reintroduced Android support libraries instead of AndroidX in order to avoid breaking changes for the users that haven't migrated to AndroidX yet.

The version 1.4.2 import ProcessLifecycleOwner from `android.arch.lifecycle:extensions:1.1.1`.

If you import to the last version but it still requires AndroidX is probably due to a dirty cache.
Would you mind cleaning the cache and let us know any outcome?
- `Build -> Clean Project`
- `File -> Invalidate Caches / Restart...`
It can require a few attempts.

If it doesn't work, please, could you provide some more info about device, stacktrace, Android version, tracker version and if it works correctly with old tracker versions (< 1.4.0)?
