### ISSUE TITLE
How to add the ScreenView tag to an Activity or Fragment

### ISSUE THREAD

**Issue by drayan85** [snowplow/snowplow-android-tracker#400]
`Tracker.java` has the following method

```
        /**
         * @param activities whether to auto-track screen views (onStart of activities)
         * @param onlyTrackLabelledScreens track only activities or fragments that have a Snowplow tag
         * @return itself
         */
        public TrackerBuilder screenviewEvents(Boolean activities,
                                               Boolean onlyTrackLabelledScreens) {
            this.activityTracking = activities;
            this.onlyTrackLabelledScreens = onlyTrackLabelledScreens;
            return this;
        }
```

In My case, I wanted to use this method to avoid some activities screen view trigger automatically rather I would like trigger manually. But I could not able to find the way to add the label to an activity or fragment in the SnowPlow documentation.

Could you please guide me on how I can add the Tag if I am using this method while I build SnowPlow Tracker.

Thank you in Advance.

**Comment by AlexBenny** [comment]
Hi @drayan85 
Thanks for raising this up to our attention.
This method is part of a feature we planned but we haven't implemented due to other priorities. It's probably ended up in the public API for mistake.

How would you like to use that feature?

Unfortunately, at the moment the autotracking ScreenView doesn't allow to filter out some activities.

A possible solution is probably to implement your [`ActivityLifecycleHandler`](https://github.com/snowplow/snowplow-android-tracker/blob/0ab5eeaf15eea7ca9562cf96dd28a034b97c668c/snowplow-tracker/src/main/java/com/snowplowanalytics/snowplow/tracker/tracker/ActivityLifecycleHandler.java) and register that to your application like we do [here](https://github.com/snowplow/snowplow-android-tracker/blob/18578a2c916f3c52b3af11847c822098aac7bd72/snowplow-tracker/src/main/java/com/snowplowanalytics/snowplow/tracker/Tracker.java#L523)

In the [body of `onActivityResumed`](https://github.com/snowplow/snowplow-android-tracker/blob/0ab5eeaf15eea7ca9562cf96dd28a034b97c668c/snowplow-tracker/src/main/java/com/snowplowanalytics/snowplow/tracker/tracker/ActivityLifecycleHandler.java#L62) you can decide which activities to filter out or which data to put in the ScreenView event.

I hope it can help.
Please, let us know for any further questions on this.

**Comment by drayan85** [comment]
Thanks, @AlexBenny for your reply, I hope we can work around as you suggested.

We have noticed some behaviour in the Firebase Screen that can update the current screen view of activity if we add additional information to the screen view and wondering this similar behaviour in the SnowPlow tracker as well.

While `tracker.screenviewEvents(true)` is enabled;

The `ActivityA` is used to attached multiple fragments, is there any way that we can override the first screen view trigger with the activity name and by sending another ScreenView Builder Event.
Example :- `tracker.track(ScreenView.builder().activityClassName(ActivityA).fragmentClassName(FragmentA).build())`

In this case, we are seeing two different `screen_view` recorded
1) `screen_view` of  an `ActivityA`  (Auto screen view event)
2) `screen_view` of an `ActivityA` along with `FragmentA` (Manual trigger using ScreenView Builder)

**Comment by AlexBenny** [comment]
Yes, the autotrackScreenView would continue to track the activities and you may generate your manual events if needed using the approach I described above.

Just make sure to set also the `name` property in the ScreenView event as it's mandatory.
The name can be whatever is helpful for you to distinguish the event.

Example:
```
ScreenView.builder()
    .name(<Activity-Fragment-Name>)
    .activityClassName(<Activity-Name>)
    .fragmentClassName(<Fragment-Name>)
    .build();
```

**Comment by drayan85** [comment]
But in this case, it will be recorded as two screen_view
1) From Auto screnViewEvent 
2) Manual trigger

Our issue is we wanted to see only one event which means we are expecting the manual trigger update the auto screen_view with additional params that we have triggered using manual screen view builder.

@AlexBenny, Is that possible?

**Comment by AlexBenny** [comment]
At the moment the autotrack ScreenView is not able to handle this case. We are keen to improve the feature in order to cover these cases, but it will happen after the release of the Android tracker v.2.0 , later this year.

Meanwhile you may use the only manual ScreenView tracking implementing your own automatic solution outside the tracker.
I think the approach can be: 

1. Disable completely the autotrack ScreenView feature.
`screenViewEvent` is false by default but you can also explicitly set it as false in the tracker configuration: `tracker.screenviewEvents(false)`.

2. Implement your lifecycle handler (eg.: MyLifecycleHandler) like we did for the tracker here: `[ActivityLifecycleHandler](https://github.com/snowplow/snowplow-android-tracker/blob/0ab5eeaf15eea7ca9562cf96dd28a034b97c668c/snowplow-tracker/src/main/java/com/snowplowanalytics/snowplow/tracker/tracker/ActivityLifecycleHandler.java)`.

3. Register your lifecycle-handler to your app just after the tracker initialisation: 
```
MyLifecycleHandler handler = new MyLifecycleHandler();
Application application = (Application)context.getApplicationContext();
application.registerActivityLifecycleCallbacks(handler);
```

4. Now your lifecycle-handler's callbacks will be called whenever an activity changes state. And you have total freedom about what to track and how to track that. Example:
```
@Override
public void onActivityResumed(Activity activity) {
    try {
        ...code where to get info about Activity and Fragments of interest...
        String screenName = ...generate an identifier for the Activity or Fragment you want to track...
        ScreenView event = ScreenView.builder()
                .name(screenName)
                .build();
        Tracker.instance().track(event);
    } catch (Exception e) {
        ...handle possible exceptions...
    }
}
```

This is just an approach. Basically it's a manual tracking of the ScreenView event. You can probably find better or alternative ways to track them for Fragments. Much depends by how your app is architected.

If you prefer to enlarge the discussion about better approaches to adopt in this case I would suggest to reach us on [Discourse forums](https://discourse.snowplowanalytics.com/), which have a wider community audience that can help to make the best use of the Snowplow infrastructure.

**Comment by drayan85** [comment]
Thanks @AlexBenny, I think this will help us for the time being by triggering manual screen view. 

I hope that we can change back to our logic after SnowPlow v2.0.
