### ISSUE TITLE
Crash when sending screen event in beta version 2.0.0

### ISSUE THREAD

**Issue by IanArb** [snowplow/snowplow-android-tracker#440]
**Describe the bug**
When I send an event the app crashes.

**To Reproduce**
Send a screen event with the following dependencies.

```kotlin
    @AnalyticsScope
    @Provides
    fun provideNetworkConfiguration(): NetworkConfiguration {
        return NetworkConfiguration(
            analyticsTrackerConfig.endpoint
        )
    }

    @AnalyticsScope
    @Provides
    fun provideTrackerConfiguration(): TrackerConfiguration {
        return TrackerConfiguration(analyticsTrackerConfig.appId)
            .logLevel(LogLevel.DEBUG)
            .installAutotracking(false)
    }

    @AnalyticsScope
    @Provides
    fun provideTrackerController(
        networkConfiguration: NetworkConfiguration,
        trackerConfiguration: TrackerConfiguration,
    ): TrackerController {
        return Snowplow.createTracker(
            analyticsTrackerConfig.context,
            analyticsTrackerConfig.namespace,
            networkConfiguration,
            trackerConfiguration
        )
    }

````

Event code:

```kotlin
    fun screenViewEvent(screenEvent: ScreenEvent) {
        trackerController.track(
            ScreenView.builder()
                .id(screenEvent.id)
                .name(screenEvent.name)
                .type(screenEvent.type)
                .previousName(screenEvent.previousName)
                .previousType(screenEvent.previousType)
                .build()
        )
    }
```
**Expected behavior**
The app should not crash.

**Screenshots**

**Device informatoin (please complete the following information):**
 - Device: Pixel 2 XL
 - OS: Android 11
 - Browser N/A
 - Version 2.0.0 beta 1

**Additional context**
`2021-04-22 11:09:30.013 7671-7671/cartrawler.integration E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cartrawler.integration, PID: 7671
    java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/lifecycle/ProcessLifecycleOwner;
        at com.snowplowanalytics.snowplow.internal.tracker.Tracker$5.run(Tracker.java:574)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.lifecycle.ProcessLifecycleOwner" on path: DexPathList[[zip file "/data/app/~~niY9nc6cWz2RINKsmkwIvw==/cartrawler.integration-CL7zSPlc7Tp8KAmxPeukTw==/base.apk"],nativeLibraryDirectories=[/data/app/~~niY9nc6cWz2RINKsmkwIvw==/cartrawler.integration-CL7zSPlc7Tp8KAmxPeukTw==/lib/arm64, /system/lib64, /system/product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.snowplowanalytics.snowplow.internal.tracker.Tracker$5.run(Tracker.java:574) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) `

**Comment by AlexBenny** [comment]
Thanks @IanArb for reporting this,

The tracker uses `androidx.lifecycle` to get information about when the app is in background or foreground.
We dismissed the Android support libraries as they were deprecated and we moved to support AndroidX.
 
Please, could you check that your `build.gradle` has `androidx.lifecycle:lifecycle-extensions` among the dependencies?
```
dependencies {
    implementation "androidx.lifecycle:lifecycle-extensions:2.2.0"
    ...
}
```
and the following properties are added to `gradle.properties`:
```
 android.useAndroidX=true
 android.enableJetifier=true
```

That should be enough to make the tracker be able to find the `ProcessLifecycleOwner` class.

Please, let us know for any update on this or any feedback for further improvements.

**Comment by IanArb** [comment]
Thanks for speedy response @AlexBenny 

Is there any demo app for 2.0.0 version? Having issues getting events sent and can't see any error logs coming through from the SDK.

**Comment by AlexBenny** [comment]
There is a demo app in the `release/2.0` branch of the repository. It's mostly used for internal testing rather than a proper example app but you can see an example of configuration of the tracker [here](https://github.com/snowplow/snowplow-android-tracker/blob/da268d1f05d34764e4b341aae0cd258e9534c075/snowplow-demo-app/src/main/java/com/snowplowanalytics/snowplowtrackerdemo/Demo.java#L355).

[Here](https://docs.snowplowanalytics.com/docs/collecting-data/collecting-from-own-applications/mobile-trackers/migration-guides/migration-guide-for-snowplow-android-tracker-sdk-from-version-1-x-to-2-0/) you can find a migration guide from 1.x to 2.0.

If you don't receive events it could be a wrong configuration of the collector endpoint.
When you specify the collector url in NetworkConfiguration there are few details to consider:
- the endpoint url can include the protocol (e.g.: `http://collector-url.com`). If you omit the schema the `https` schema will be set by default.
- the method can be GET or POST, if not specified POST will be set by default.

For example: `NetworkConfiguration("http://192.168.99.101:9090", HttpMethod.GET)`

I suggest to send a simple event like Timing for a first test:
`tracker.track( new Timing("category", "variable", "timing") );`

You posted:
```kotlin
fun screenViewEvent(screenEvent: ScreenEvent) {
        trackerController.track(
            ScreenView.builder()
                .id(screenEvent.id)
                .name(screenEvent.name)
                .type(screenEvent.type)
                .previousName(screenEvent.previousName)
                .previousType(screenEvent.previousType)
                .build()
        )
    }
```
You could just send it as (example in Java):
```java
        trackerController.track(
                new ScreenView("name")
                        .type("type")
        );
```
If you use the builder (already present in the v.1.x) you should pass a UUID string.
In the v2, you don't need to pass any string, the id is automatically generated. You can set your UUID but it's important it's conform to UUID format otherwise the ScreenView event would be discarded.
Also, the fields `previousName` and `previousType` are automatically filled by the tracker, but feel free to override them passing params if you prefer.

**Comment by IanArb** [comment]
Hey @AlexBenny thanks for the extra info and I've tried demo app. The issue was that I was using http protocol instead of https. Android has a feature that prevents any http protocol for security reasons. 

Also would it be a good idea to have the sessionContext and lifecycle configuration for the tracker to be disabled by default? Argument would be that it requires you to add an additional dependency and in my use case I don't need foreground and background tracking.

**Comment by AlexBenny** [comment]
Thanks @IanArb , that's a very good point.
I'm going to close this issue as it seems resolved.

Please, If you have any other feedback or idea of improvements about this beta release feel free to contact us here or on our Discourse forum: https://discourse.snowplowanalytics.com/t/snowplow-android-tracker-2-0-0-beta-1-release
