### ISSUE TITLE
Enable updating collector endpoint while Emitter is running

### ISSUE THREAD

**Issue by sofi-kry** [snowplow/snowplow-android-tracker#508]
**Describe the bug**
Updating the tracker endpoint doesn't work.

**To Reproduce**
I tried 2 things:

1- Having an instance of the `TrackerController`, which is initialized at startup:
```
trackerController.network?.endpoint = NEW_ENDPOINT
```

2- Using the default tracker controller:
```
Snowplow.getDefaultTracker()?.network?.endpoint = NEW_ENDPOINT
```

In both cases I still see requests being made to the same old endpoint.

I'm using Snowplow version 3.0.3.

**Expected behavior**
The endpoint is updated and events are sent to `NEW_ENDPOINT`.

**Comment by matus-tomlein** [comment]
This issue was solved in version 3.1.1 of the Android tracker. Just to give some more details on the investigation and solution, I am reposting the information from the PR:

I found that there are two possible reasons for this issue:

1. the Emitter is currently running, or
2. it uses a custom network connection.

I don't think that anything should happen in the second case. It sounds reasonable that custom network connections are not updated by setting the endpoint in tracker controller (let me know if you think otherwise).

But the first case is less intuitive and can be a problem for several reasons:

- the Tracker calls `flush()` on Emitter right after initialisation which means that the Emitter starts running and it is not possible to update the endpoint right after the tracker is initialised, and
- Emitters can be running for quite a long time. Even when all events are sent, `attemptEmit()` function goes to sleep a number of times checking for new events.

So I think it's reasonable to enable updating the network configuration while the Emitter is running. This PR enables that and removes the check from setters for network configuration in Emitter. I didn't want to have the network connection change during emitting and so I made the `attemptEmit` function accept a `NetworkConnection` to be used while it is running. The network connection is only refreshed in the `attemptEmit` after the sleep while waiting for new events.
